### ISSUE TITLE
Run image similarity search demo using docker container version of deepdetect

### ISSUE THREAD

**Issue by anguoyang** [beniz/deepdetect#137]
Hi, @beniz ,

I want to try the image search demo on docker image, it seems the pip has not been installed, so I try to install it, but failed due to permission error --- I have no permission on the python directory, when I try to  install it with "sudo", it ask me for the password of dd, unfortunately,  I don't know the password:), so i could not install the pip.

**Comment by beniz** [comment]
You should install the demo dependencies on your own system, then run the docker. Search demo should just run fine then. Let us know how it goes.

**Comment by anguoyang** [comment]
do you mean "install annoy" on host machine?
I did it with "pip install annoy", however got these errors:
src/annoymodule.cc:17:20: fatal error: Python.h: No such file or directory

 #include "Python.h"

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/annoy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-T6rNTe-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/annoy
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

**Comment by anguoyang** [comment]
hi, @beniz ,

I have installed the annoy on my host successfully, and then run the docker, but still with the same error:
Traceback (most recent call last):
  File "imgsearch.py", line 6, in <module>
    from annoy import AnnoyIndex
ImportError: No module named annoy

it seems that I have to install annoy within the container

**Comment by beniz** [comment]
No, it's your annoy installation that is not working. The `imgsearch.py` file communicates with a remote deepdetect server, that can be native or docker, it doesn't matter.

**Comment by anguoyang** [comment]
I prefer to use the imgsearch.py natively, but deepdetect server in docker.
When I use the imgsearch,py, do I need to modify the source code, so it could point to the right docker server?

**Comment by anguoyang** [comment]
I mean, is the imgsearch.py communicate with the deepdetect server in docker through JSON/http?
just as predict or other interfaces?

**Comment by beniz** [comment]
Yes the script should communicate without changes even if your server is running from docker.

**Comment by anguoyang** [comment]
I  built deepdetect on my host(ubuntu) today successfully, when I run the imgsearch demo, I got this error:

Traceback (most recent call last):
  File "imgsearch.py", line 8, in <module>
    import cv2
ImportError: No module named cv2

It seems that I all need to install python-opencv and other dependencies

**Comment by anguoyang** [comment]
After I installed python-opencv, still got this error:

0/2557Traceback (most recent call last):
  File "imgsearch.py", line 78, in <module>
    for p in classif['body']['predictions']:
KeyError: 'body'

**Comment by beniz** [comment]
There's no error catching in the demo script, this means there was an error predicting over your image. Check the image file, check that a simple `predict` API call works for that image, and then go back to image search.

**Comment by beniz** [comment]
No activity > 15 days, closing.

**Comment by luqezman** [comment]
[sudo] password for dd: ? :'( I'm inside in a docker container :P

**Comment by beniz** [comment]
Docker images have no root access. Look docker documentation up and run root bash at container startup.

**Comment by luqezman** [comment]
Hi @beniz, the problem number one was resolved successfully.

I have another problem(Yes, I already did a search):

Where I need to put the "models" folder? I'm trying to setup a "Text-Training.

Im following this link -> http://www.deepdetect.com/tutorials/txt-training/

**Comment by beniz** [comment]
Anywhere you want as long as you are passing the whole path to the API

**Comment by luqezman** [comment]
Done with success ;) I was thinking dat deepdetect had a default path for models :(
