### ISSUE TITLE
Switching to pool5/7x7_s1 gives an error

### ISSUE THREAD

**Issue by dgtlmoon** [beniz/deepdetect#191]
Using `imgsearch.py`, I trained with 1995 images, changed `extract_layer=loss3/classifier` to `extract_layer=pool5/7x7_s1` as per https://github.com/beniz/deepdetect/tree/master/demo/imgsearch 

Then ran `python imgsearch.py --search /images/0322d9a396dae12698c43799cc90c2ed.jpg`

I am using `ggnet`

```
Traceback (most recent call last):
  File "imgsearch.py", line 109, in <module>
    near = u.get_nns_by_vector(classif['body']['predictions'][0]['vals'],args.search_size,include_distances=True)
  File "/usr/local/lib/python2.7/dist-packages/annoy/__init__.py", line 56, in get_nns_by_vector
    return super(AnnoyIndex, self).get_nns_by_vector(self.check_list(vector), n, search_k, include_distances)
  File "/usr/local/lib/python2.7/dist-packages/annoy/__init__.py", line 31, in check_list
    raise IndexError('Vector must be of length %d' % self.f)
IndexError: Vector must be of length 1000
```

I see the following output that the layer is ignored, is this related?
```

INFO - 21:04:10 - Network initialization done.
INFO - 21:04:10 - Attempting to upgrade input file specified using deprecated V1LayerParameter: /opt/models/ggnet/bvlc_googlenet.caffemodel
INFO - 21:04:10 - Successfully upgraded file specified using deprecated V1LayerParameter
INFO - 21:04:10 - Ignoring source layer data
INFO - 21:04:10 - Ignoring source layer label_data_1_split
INFO - 21:04:10 - Ignoring source layer loss1/ave_pool
INFO - 21:04:10 - Ignoring source layer loss1/conv
INFO - 21:04:10 - Ignoring source layer loss1/relu_conv
INFO - 21:04:10 - Ignoring source layer loss1/fc
INFO - 21:04:10 - Ignoring source layer loss1/relu_fc
INFO - 21:04:10 - Ignoring source layer loss1/drop_fc
INFO - 21:04:10 - Ignoring source layer loss1/classifier
INFO - 21:04:10 - Ignoring source layer loss1/loss
INFO - 21:04:10 - Ignoring source layer loss2/ave_pool
INFO - 21:04:10 - Ignoring source layer loss2/conv
INFO - 21:04:10 - Ignoring source layer loss2/relu_conv
INFO - 21:04:10 - Ignoring source layer loss2/fc
INFO - 21:04:10 - Ignoring source layer loss2/relu_fc
INFO - 21:04:10 - Ignoring source layer loss2/drop_fc
INFO - 21:04:10 - Ignoring source layer loss2/classifier
INFO - 21:04:10 - Ignoring source layer loss2/loss
INFO - 21:04:10 - Ignoring source layer pool5/drop_7x7_s1
```

I have to add that using the default extract_layer there is no problems

thanks!

**Comment by beniz** [comment]
The error log tells you all. `loss3` and `pool5` do not have the same size. Reindex with pool5. Better bring these conversations to gitter when you are not sure.
